backend:
  name: github
  repo: judi-ca/animezonquotes  # Remplace par ton repo GitHub
  branch: main  # ou master selon ton repo

media_folder: "assets/images"   # où stocker les images et animations
public_folder: "/assets/images"

collections:
  - name: "quotes"
    label: "Citations"
    folder: "content/quotes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Citation", name: "text", widget: "string" }
      - { label: "Auteur", name: "author", widget: "string" }
      - { label: "Animation URL", name: "animation", widget: "string" }