backend:
  name: git-gateway
  branch: master  # ou main selon ton dépôt

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "quotes"
    label: "Citations"
    folder: "content/quotes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Citation", name: "text", widget: "string" }
      - { label: "Auteur", name: "author", widget: "string" }
      - { label: "Animation URL", name: "animation", widget: "string" }
