backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "citations"
    label: "Citations"
    folder: "content/citations"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "author", label: "Auteur", widget: "string" }
      - { name: "quote", label: "Citation", widget: "text" }
      - { name: "image", label: "Image", widget: "image" }
