backend:
  name: github
  repo: "judi-co/animzonquotes"   # Remplace par ton repo
  branch: master                  # Branche principale
  token: "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"  # Ton token

media_folder: "images"
public_folder: "/images"

collections:
  - name: "quotes"
    label: "Citations"
    folder: "content/quotes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Anime", name: "anime", widget: "string" }
      - { label: "Personnage", name: "character", widget: "string" }
      - { label: "Citation", name: "quote", widget: "text" }

