backend:
  name: git-gateway
  branch: master

media_folder: "images"
public_folder: "/images"

collections:
  - name: "quotes"
    label: "Citations"
    folder: "content/quotes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Anime", name: "anime", widget: "string", required: true }
      - { label: "Personnage", name: "character", widget: "string", required: true }
      - { label: "Citation", name: "quote", widget: "text", required: true }
      - { label: "Image (optionnelle)", name: "image", widget: "image", required: false }
